development:
  adapter: postgresql
  encoding: unicode
  database: new1
  host    : localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: new1
  host    : localhost
  username: postgres
  password: postgres
